version: '3.8'

services:
  api:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - API_ENDPOINT=http://api:8000
    depends_on:
      - api
    restart: unless-stopped
